apiVersion: v2
name: pet-battle-api-test
description: A Helm chart for Kubernetes
type: application
version: 0.0.44
appVersion: pet-battle-api-test-jenkins.44
home: https://eformat.github.io/helm-charts
maintainers:
- name: eformat
