apiVersion: v2
name: pet-battle-api
description: A Helm chart for Kubernetes
type: application
version: 0.0.53
appVersion: pet-battle-api-test-jenkins.59
home: https://eformat.github.io/helm-charts
maintainers:
- name: eformat
