---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pet-battle-api
  labels:
    app: {{ .Values.appName }}
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        openshift.io/imported-from: quay.io/eformat/pet-battle-api:latest
      from:
        kind: DockerImage
        name: quay.io/eformat/pet-battle-api:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
