---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pet-battle-api
  labels:
    app: {{ .Values.appName }}
  creationTimestamp: null
spec:
  tags:
    - annotations:
        openshift.io/imported-from: eformat/pet-battle-api
      from:
        kind: DockerImage
        name: {{ .Values.image_repository }}/{{ .Values.image_namespace }}/{{ .Values.image_name }}:{{ .Chart.AppVersion }}
      importPolicy: {}
      name: {{ .Chart.AppVersion }}
