---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pet-battle-api
  labels:
    app: {{ .Values.appName }}
  creationTimestamp: null
spec:
  tags:
    - annotations:
        openshift.io/imported-from: eformat/pet-battle-api
      from:
        kind: DockerImage
        name: quay.io/eformat/pet-battle-api:latest
      importPolicy: {}
      name: latest
