{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/component: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ .Values.appName }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
{{ end }}
