apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: petbattleapis.app.petbattle
spec:
  group: app.petbattle
  names:
    kind: PetBattleApi
    listKind: PetBattleApiList
    plural: petbattleapis
    singular: petbattleapi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
